### ISSUE TITLE
Allow Edits on all aspects of a PC

### ISSUE THREAD

**Issue by Mazzmnza42** [artg3-dev/DM_Tools#48]
**Is your feature request related to a problem? Please describe.**
When using the **Edit PC** button to edit a selected PC, not all fields are editable. some are grayed out.

**Describe the solution you'd like**
Allow every field to be editable.

**Additional context**
Sometimes Characters might change their name, or the DM might make a typo.

**Comment by artg3-dev** [comment]
I wasnt sure if you should be able to change things like race and class permanently, because are they then the same character? Maybe if it's a temporary effect like a curse/magic etc. Maybe I should add a feature to change some stuff, but retain the information of past races/classes. Thoughts on this?

**Comment by Mazzmnza42** [comment]
I think players can keep track of their past races/classes. The ability to edit would mostly be for fixing mistakes. I don't think there is much to lose by allowing all fields to be edited.

**Comment by artg3-dev** [comment]
The eventual plan is to have this used by both dms and players simultaneously

**Comment by artg3-dev** [comment]
Just checked the code for this and it should be really easy to implement. Will fix at some point soon.
